@TOKEN=eyJhbGciOiJIUzM4NCJ9.eyJmdWxsbmFtZSI6Im5hbWUgbGFzdG5hbWUiLCJzdWIiOiJlbWFpbEB0ZXN0LmNvbSIsImlhdCI6MTc4MTgxOTE5MCwiZXhwIjoxNzgxOTA1NTkwLCJhdXRob3JpdGllcyI6WyJST0xFX0NMSUVOVCJdfQ.AdiSME39mRYq81LqWkH3ed2izkgn6gtwAOQbzZutwlCODahq5be3HwkRG0OCgvzp
@URL=http://localhost:8080/api/v1



### Get All accounts
GET {{URL}}/accounts
Authorization: Bearer {{TOKEN}}

### Get Single account
GET {{URL}}/accounts/1
Authorization: Bearer {{TOKEN}}


### CREAR ACCOUNT
POST {{URL}}/accounts
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name":"delete account",
    "accountType":"BANK",
    "color":"#99ec14",
    "currency":"MXN",
    "balance":1000.55
}

### update ACCOUNT
PATCH {{URL}}/accounts/1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name":"My first Account",
    "accountType":"BANK",
    "color":"#4c1c74",
    "currency":"MXN",
    "balance":1000.55
}

### delete  account
DELETE {{URL}}/accounts/2
Authorization: Bearer {{TOKEN}}

