
@TOKEN=eyJhbGciOiJIUzM4NCJ9.eyJmdWxsbmFtZSI6IlVzdWFyaW8gVW5vIHVzdWFyaW8gdW5vIiwic3ViIjoidXNlcjFAdGVzdC5jb20iLCJpYXQiOjE3ODg0NzEwMjIsImV4cCI6MTc4ODU1NzQyMiwidG9rZW5UeXBlIjoiQUNDRVNTIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DTElFTlQiXX0.WE4ZOcKNGe8wutDmzlHKEs1CCpWC9JkLhqtQnOs-4co6K_M9ULKlDlp91CqffXza

@REFRESH_TOKEN=eyJhbGciOiJIUzM4NCJ9.eyJmdWxsbmFtZSI6IlVzdWFyaW8gVW5vIHVzdWFyaW8gdW5vIiwic3ViIjoidXNlcjFAdGVzdC5jb20iLCJpYXQiOjE3ODg0NzA5OTcsImV4cCI6MTc4OTA3NTc5NywidG9rZW5UeXBlIjoiUkVGUkVTSCIsImF1dGhvcml0aWVzIjpbIlJPTEVfQ0xJRU5UIl19.j8FzRvsDlmph9kUUiRUpA1F6DTwhv29q5X0cc2X_iJUHsQfNLFbSe7JKzcwQL-Nq

@URL=http://localhost:8080/api/v1


### Register 

POST {{URL}}/auth/register
Content-Type: application/json

{
    "firstName": "test_1",
    "lastName": "test_1_lastname",
    "email": "test_1@ttest-currency.com",
    "password": "12345678",
    "preferredCurrency":"MXN"
}


### Login 

POST {{URL}}/auth/login
Content-Type: application/json

{
    "email": "user1@test.com",
    "password": "12345678"
}

### Logout 

POST {{URL}}/auth/logout
Authorization: Bearer {{TOKEN}}

### Refresh token (public, no Bearer required)

POST {{URL}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{REFRESH_TOKEN}}"
}


