@TOKEN=eyJhbGciOiJIUzM4NCJ9.eyJmdWxsbmFtZSI6IlVzdWFyaW8gVW5vIHVzdWFyaW8gdW5vIiwic3ViIjoidXNlcjFAdGVzdC5jb20iLCJpYXQiOjE3ODkwNTU0OTUsImV4cCI6MTc4OTE0MTg5NSwidG9rZW5UeXBlIjoiQUNDRVNTIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DTElFTlQiXX0.rHvN5cYjJTSWV9wXP43d3X7GkB--n1nQwXpcuxAtQ9Nouq8yzBcc2jhXURjaD17W
@URL=http://localhost:8080/api/v1/budgets



### Get All budget
GET {{URL}}
Authorization: Bearer {{TOKEN}}

### Get Single account
GET {{URL}}/5
Authorization: Bearer {{TOKEN}}


### CREAR budget
POST {{URL}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "categoryId":1,
    "month":"2026-10-14",
    "amount":5000,
    "alertThreshold":"70",
    "notes":"My first budget"
}

### update ACCOUNT
PATCH {{URL}}/1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json
{
    "amount":500,
    "alertThreshold":"70",
    "notes":"My first budget"
}

### delete  account
DELETE {{URL}}/2
Authorization: Bearer {{TOKEN}}

