@TOKEN=eyJhbGciOiJIUzM4NCJ9.eyJmdWxsbmFtZSI6Im5hbWUgbGFzdG5hbWUiLCJzdWIiOiJlbWFpbEB0ZXN0LmNvbSIsImlhdCI6MTc4MTgxOTE5MCwiZXhwIjoxNzgxOTA1NTkwLCJhdXRob3JpdGllcyI6WyJST0xFX0NMSUVOVCJdfQ.AdiSME39mRYq81LqWkH3ed2izkgn6gtwAOQbzZutwlCODahq5be3HwkRG0OCgvzp
@URL=http://localhost:8080/api/v1

### Get All categories
GET {{URL}}/categories
Authorization: Bearer {{TOKEN}}

### Get Single category
GET {{URL}}/categories/1
Authorization: Bearer {{TOKEN}}

### create  category
POST {{URL}}/categories
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name":"delete category",
    "categoryType":"INCOME",
    "color":"#4c1c74"
}

### update  category
PATCH {{URL}}/categories/1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name":"My first category edit",
    "categoryType":"INCOME",
    "color":"#4c1c74"
}

### delete  category
DELETE {{URL}}/categories/3
Authorization: Bearer {{TOKEN}}

