@TOKEN=eyJhbGciOiJIUzM4NCJ9.eyJmdWxsbmFtZSI6IlVzdWFyaW8gVW5vIHVzdWFyaW8gdW5vIiwic3ViIjoidXNlcjFAdGVzdC5jb20iLCJpYXQiOjE3ODQwNDY5MDEsImV4cCI6MTc4NDEzMzMwMSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DTElFTlQiXX0.QqNRZXbuq-rJ8FWmvl9tyoyz2o6PegzTK2kort-L8XXk3FpGjdgwqYI9FJOyJIHS
@URL=http://localhost:8080/api/v1

### Get All categories
GET {{URL}}/categories
Authorization: Bearer {{TOKEN}}

### Get Single category
GET {{URL}}/categories/1
Authorization: Bearer {{TOKEN}}

### create  category
POST {{URL}}/categories
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name":"delete category",
    "categoryType":"INCOME",
    "color":"#4c1c74"
}

### update  category
PATCH {{URL}}/categories/1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name":"My first category edit",
    "categoryType":"INCOME",
    "color":"#4c1c74"
}

### delete  category
DELETE {{URL}}/categories/3
Authorization: Bearer {{TOKEN}}

