
@TOKEN=eyJhbGciOiJIUzM4NCJ9.eyJmdWxsbmFtZSI6Im5hbWUgbGFzdG5hbWUiLCJzdWIiOiJlbWFpbEB0ZXN0LmNvbSIsImlhdCI6MTc4MTgxOTE5MCwiZXhwIjoxNzgxOTA1NTkwLCJhdXRob3JpdGllcyI6WyJST0xFX0NMSUVOVCJdfQ.AdiSME39mRYq81LqWkH3ed2izkgn6gtwAOQbzZutwlCODahq5be3HwkRG0OCgvzp
@URL=http://localhost:8080/api/transfer

### Save transaction INCOME
POST {{URL}}
Authorization: Bearer {{TOKEN}}
{
    "accountId" :1,
    "categoryId":1,
    "transactionType" : "INCOME",
    "amount":15000
}

### Save transaction EXPENSE
POST {{URL}}
Authorization: Bearer {{TOKEN}}
{
    "accountId" :1,
    "categoryId":1,
    "transactionType" : "EXPENSE",
    "amount":1000
}

### Ver todo (Página 0, de 10 en 10):
GET {{URL}}
Authorization: Bearer {{TOKEN}}

### Ver solo gastos de una cuenta específica:
GET {{URL}}?type=EXPENSE&accountId=2
Authorization: Bearer {{TOKEN}}

### Ver transacciones en un rango de fechas:
GET {{URL}}?start=2026-06-01T00:00:00&end=2026-06-30T23:59:59
Authorization: Bearer {{TOKEN}}

# LocalDate month = request.month().withDayOfMonth(1);